//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevKit.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevKitEntities : DbContext
    {
        public DevKitEntities()
            : base("name=DevKitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<StoredProcedure> StoredProcedures { get; set; }
        public DbSet<DBServer> DBServers { get; set; }
        public DbSet<DBScriptSession> DBScriptSessions { get; set; }
    }
}
